name: GitHub for IT Pro CI/CD Pipeline

env:
  OUTPUT_PATH: ${{ github.workspace }}

on: [push]

jobs:
      
  # Deploy VM in Azure
  DeployVM:
    runs-on: windows-latest

    steps:
    # checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1

    - name: look for ps1 file
      run: |
        ls '${{ env.OUTPUT_PATH }}'
        
    - name: provision virtual machine in azure
      env:
        RESOURCE_GROUP: rg-githubitpro
        RESOURCE_GROUP_REGION: southcentralus
        SERVER_NAME: gihtubactions
        ADMIN_LOGIN: matt
      run: >
        powershell -command "& '${{ env.OUTPUT_PATH }}\CreateVM.ps1'"

 

